name: car_admin_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auth:
    path: ../shared/auth/
  bloc: ^8.1.4
  build_runner: ^2.4.11
  cached_network_image: ^3.3.1
  core:
    path: ../shared/core/
  cupertino_icons: ^1.0.8
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  get_it: ^7.7.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  persistent_bottom_nav_bar_2: ^5.0.3
  supabase_flutter: ^2.5.8

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  melos: ^6.1.0
  freezed: ^2.5.2
  injectable_generator: null
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

# ? dart pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "../assets/images/car_admin_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# ? dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: "../assets/images/white_background.png"
  android_12:
    color: "#ffffff"
    image: "../assets/images/white_background.png"

assets:
  - ../assets/images/
  - ../assets/lottie/
  - ../assets/svg/
  - ../assets/png/
