name: auth
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  core:
    path: ../core/
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^7.7.0
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  supabase_flutter: ^2.5.8

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: 
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true

assets:
  - ../../assets/images/
  - ../../assets/lottie/
  - ../../assets/svg/
