name: core
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  admin_home:
    path: ../../../apps/car_admin_app/packages/admin_home/
  auth:
    path: ../auth/
  bloc: ^8.1.4
  dots_indicator: ^3.0.0
  envied: ^0.5.4+1
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  user_home:
    path: ../../../apps/car_user_app/packages/user_home/

dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - ../../assets/images/
    - ../../assets/lottie/
    - ../../assets/svg/
    - ../../assets/png/

