name: core
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  auth:
    path: ../auth/
  bloc: ^8.1.4
  dartz: ^0.10.1
  dots_indicator: ^3.0.0
  envied: ^0.5.4+1
  equatable: ^2.0.5
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  injectable: ^2.4.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.1.2
  persistent_bottom_nav_bar_2: ^5.0.3
  shimmer: ^3.0.0
  supabase_flutter: ^2.5.8
  user_home:
    path: ../../../apps/car_user_app/packages/user_home/

dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: null
  json_serializable: ^6.8.0

flutter:
  assets:
    - ../../assets/images/
    - ../../assets/lottie/
    - ../../assets/svg/
    - ../../assets/png/
