name: user_home
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  auth:
    path: ../../../shared/auth/
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  core:
    path: ../../../shared/core/
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  persistent_bottom_nav_bar_2: ^5.0.3
  supabase: ^2.2.5
  supabase_flutter: ^2.5.9
  syncfusion_flutter_datepicker: ^26.1.42
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  injectable: ^2.4.2
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed: ^2.5.2
  injectable_generator: 
  json_serializable: ^6.8.0

flutter: 
