name: user_home
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  carousel_slider: ^4.2.1
  core:
    path: ../../../shared/core/
  auth: 
    path: ../../../shared/auth/
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  persistent_bottom_nav_bar_2: ^5.0.3
  syncfusion_flutter_datepicker: ^26.1.42

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter: null
